services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: onlinestore-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - onlinestore-data:/var/opt/mssql
      - ./:/workspace:ro

volumes:
  onlinestore-data:
